/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.rolandhe.thrift.enhancer.test;


public enum AdStyle implements org.apache.thrift.TEnum {
  WORD(0),
  IMAGE(1);

  private final int value;

  private AdStyle(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AdStyle findByValue(int value) { 
    switch (value) {
      case 0:
        return WORD;
      case 1:
        return IMAGE;
      default:
        return null;
    }
  }
}
